config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  get 'notification', to: 'pages#notification', as: 'notification'
  resources :entertainments, only: [ :index, :show ] do
    collection do
      get :map
    end
    resources :entertainment_applications, only: [ :new, :create ] do
      collection { get :confirmation }
    end
  end
  resources :entertainment_applications, only: [:destroy] do
    member {
      patch :accept
      patch :refused
      patch :first_accept
    }

  end
  resources :events, only: [ :new, :create, :show ]

  resource :dashboard, only: [ :show ]

  resources :chats, only: [ :index, :show ] do
    resources :messages, only: [ :create ]
  end

  resource :epk, except: [:destroy, :create, :new]

  resources :availabilities, except: [:index, :show, :destroy]
end

app/models/entertainment.rb
class Entertainment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true
  has_many :entertainment_applications, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_address,
    associated_against: {
      event: [ :address]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/entertainments_controller.rb
class EntertainmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show, :map ]
  before_action :set_entertainment, only: [:show]

  def index
    @entertainments = policy_scope(Entertainment.joins(:event).where(user: nil).where("date >= ?", Date.today)).order(starts_at: :asc)
    if params[:query].present?
      @entertainments = @entertainments.search_by_address(params[:query])
    end
  end

  def show
    authorize @entertainment
    @entertainment_applications = @entertainment.entertainment_applications.where(status: "Accepté")
    @artist_number = @entertainment.event.number_of_artists_needed - @entertainment_applications.count
    @entertainment = Entertainment.find(params[:id])

    @user_has_applied = current_user&.entertainment_applications&.find_by(entertainment: @entertainment, status: ["En cours", "Accepté", "Validé"])
    @is_proposed = current_user&.entertainment_applications&.find_by(entertainment: @entertainment, status: "Proposé")
    # @user_has_applied = Entertainment_applications.where(entertainment: @entertainment, user: current_user)
    @entertainment_application = current_user&.entertainment_applications&.find_by(entertainment: @entertainment)
    @entertainment_chat = @entertainment_application&.chat
  end

  def map
  @events = Event.all
  authorize @events
  @markers = @events.map do |event|
    {
      lat: event.latitude,
      lng: event.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { event: event }),
      marker_html: render_to_string(partial: "marker", locals: {event: event})
    }
  end
  end

  private

  def set_entertainment
    @entertainment = Entertainment.find(params[:id])
  end
end

app/views/entertainments/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"], class: 'mapboxgl-ctrl-geocoder'}}
%>

app/views/entertainments/_info_window.html.erb
 <div class="popup-container">
  <h3 class="popup-title"><%= event.name %></h3>
  <p class="popup-address"><%= event.address %></p>
  <p class='popup-date'><%= l(event.date, format: '%d/%m/%Y') %></p>

  <div class="entertainments-grid">
    <% event.entertainments.each do |entertainment| %>
      <%= link_to entertainment_path(entertainment), class: "entertainment-link" do %>
        <div class="entertainment-instruments">
          <% if entertainment.instruments.include?('Chanteur') && entertainment.artist_type == 'Soliste' %>
            <% ordered_instruments = entertainment.instruments.partition { |i| i == 'Chanteur' }.flatten %>
            <p class='artist-type'>Recherche un <%= ordered_instruments.join(' / ') %></p>
          <% else %>
            <p class="artist-type">Recherche <%= entertainment.artist_type %> avec </p>
            <% if entertainment.instruments.any? %>
              <p class="artist-type"><%= entertainment.instruments.join(', ') %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entertainments/_marker.html.erb
<i class="fas fa-location-dot text-danger fs-4"></i>

app/views/entertainments/index.html.erb
<div class="container.entertainement">

  <div class="container-header">
      <%= link_to root_path do %>
        <%= image_tag "lyltatent_logo.png", alt: "Ma photo", class: "lyl-logo-entertainments" %>
      <% end %>
      <% if user_signed_in? %>
        <% if current_user.role == "artiste" %>
          <%= link_to  "Organisateur",
              destroy_user_session_path,
              methode: :delete,
              data: { turbo_method: :delete, turbo_confirm: "Vous allez être déconnecté pour vous reconnecter en tant qu'organisateur. Continuer ?"},
              class: "top-right-btn btn-orga" %>
        <% elsif current_user.role == "organisateur d'événements" %>
          <%= link_to " Artiste",
              destroy_user_session_path,
              method: :delete,
              class: "top-right-btn btn-orga",
              data: {
                turbo_method: :delete, turbo_confirm: "Vous allez être déconnecté pour vous reconnecter en tant qu'artiste. Continuer ?"
              } %>
        <% end %>
      <% else %>
        <%= link_to "Se connecter", new_user_session_path, class: "top-right-btn btn-orga" %>
      <% end %>
  </div>

  <div class="search-bar">
    <%= form_with url: entertainments_path, method: :get, class: "search-form", local: true do %>
        <div class="input-wrapper">
          <%= text_field_tag :query, params[:query], class: "search-input", placeholder: "Tape une ville..." %>
          <button type="submit" class="search-btn">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </div>
    <% end %>
  </div>

  <h1 id="title-entertainment">Événements à venir</h1>
    <p id="sous-entertainment">En Recherche d'Artiste</p>

  <div class="button">
    <%= link_to "Liste | Carte", map_entertainments_path, class: "btn-white" %>
  </div>

  <% if @entertainments.empty? %>
    <div class="no-entertainments">
      <p>Pas d'événements disponibles dans cette ville. Revenez plus tard !</p>
    </div>
  <% else %>
  <div class="entertainments-cards">
    <% @entertainments.each do |entertainment| %>
      <%= link_to entertainment_path(entertainment), class: "entertainment-card-link" do %>
        <div class="entertainment-card">
          <% if entertainment.event.photo.attached? %>
            <%= cl_image_tag(entertainment.event.photo.key, height: 160, width: 250, crop: :fill, alt: "Image de l'événement", class: "card-image") %>
          <% else %>
           <%= image_tag "default_event.jpg", alt: "Image par défaut" %>
          <% end %>

          <div class="card-content">
            <h3><%= entertainment.event.name %></h3>
            <p><i class="fas fa-solid fa-calendar-days me-2" style="margin-right: 8px;"></i><%= l(entertainment.event.date, format: '%d/%m/%Y') %></p>
            <p><i class="fas fa-music" style="margin-right: 4px;"></i> Ambience <%= entertainment.event.musical_styles.join(', ') %></p>
            <%if entertainment.instruments.include?('Chanteur') && entertainment.artist_type == 'Soliste'%>
              <% ordered_instruments = entertainment.instruments.partition { |i| i == 'Chanteur' }.flatten %>
              <p> <i class="fas fa-search" style="margin-right: 3px;"></i>  Recherche un <%= ordered_instruments.join(' / ') %></p>
            <% else %>
              <p><i class="fas fa-search" style="margin-right: 3px;"></i>   Recherche <%= entertainment.artist_type %> avec : </p>
              <% if entertainment.instruments.any?  %>
                <p class='instrument-margin'> <%= entertainment.instruments.join(', ') %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/entertainments/map.html.erb
<div style="width: 100%; height: 100vh;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/entertainments/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@entertainment.event.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @entertainment.event.description %>
<% if @entertainment.event.photo.attached? %>
  <% content_for :meta_image, cl_image_path(@entertainment.event.photo.key) %>
<% else %>
  <% content_for :meta_image, image_path("default_event.jpg") %>
<% end %>

<div id='entertainment-container'>
  <div class="event-image-container">
    <% if @entertainment.event.photo.attached? %>
          <%= cl_image_tag @entertainment.event.photo.key, height: 300, width: 300, crop: :fill, class: 'event-image'%>
    <% else %>
          <%= image_tag "default_event.jpg", alt: "image par défaut", class: 'event-image' %>
    <% end %>
  </div>

  <div class="text-container">
    <h2 class="text-center text-bold"><%= @entertainment.event.name %></h2>
    <br>


  <h4><%= @entertainment.event.description %></h4>
  <br>
     <p><i class="fa-solid fa-location-dot me-2"></i><%=@entertainment.event.address%></p>
    <p><i class="fa-solid fa-calendar-days me-2"></i><%= l(@entertainment.event.date, format: '%d/%m/%Y') %></p>
    <p><i class="fa-solid fa-clock me-2"></i>De: <%= l(@entertainment.starts_at, format: '%Hh%M' ) %></p>
    <p><i class="fa-solid fa-clock me-2"></i>À: <%= l(Time.at(@entertainment.duration_in_minutes * 60).utc, format: '%Hh%M') %></p>
     <p><i class="fa-solid fa-hourglass-start me-2"></i>Durée: <%= l(Time.at(@entertainment.event.duration * 60).utc, format: '%Hh%M') %></p>
    <p> <i class="fa-solid fa-people-group me-2"></i> Public attendu: <%= @entertainment.event.estimated_public_in_number %> personnes
    et l'âge est d'environ <%= @entertainment.event.public_age %> ans</p>



      <div class='musical-style-card-container'>
        <% @entertainment.event.musical_styles.each do |style| %>
           <div class='musical-style-card'><%= style %></div>
        <% end %>
      </div>

    <div class='separator'></div>

    <div class="condition-container">
    <p class="text-bold"> Rémunération :</p>

    <%= @entertainment.planned_remuneration%> <i class="fa-solid fa-scale-balanced"></i>

    <% if @entertainment.planned_remuneration_in_euros.present? %>
      <p><%= @entertainment.planned_remuneration_in_euros %> <i class="fa-solid fa-euro-sign"></i></p>
    <% end %>

    <p class="text-bold">Sont pris en charge:</p>
      <%= @entertainment.included_services.join(', ') %>
  </div>


<div class="flex-space-between">
    <% if @is_proposed %>
        <%=  link_to "Accepter",first_accept_entertainment_application_path(@is_proposed), class:"bottom-middle-btn", data: {turbo_method: :patch}%>
        <%=  link_to "Refuser", refused_entertainment_application_path(@is_proposed), class:"bottom-middle-btn", data: { turbo_confirm: "Es-tu sûr de vouloir refuser ce spectacle ?", turbo_method: :patch } %>
    <% elsif @user_has_applied  %>
      <% if @entertainment_chat %>
        <%= link_to chat_path(@entertainment_chat), class: "btn-rounded" do %>
          <i class="fa-solid fa-message"></i>
        <% end %>
      <% end %>

        <%= link_to entertainment_application_path(@entertainment_application),
                    data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette candidature ?" },
                    class: "btn-rounded" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>

    <% else %>
      <%= link_to "Postuler", new_entertainment_entertainment_application_path(@entertainment), class: "bottom-middle-btn" %>
    <% end %>
  </div>


    <div class="text-bold-center">
      <h4>Ils participent à l'événement</h4>
    </div>
  </div>

  <div class="user-image-container">
    <% @entertainment_applications.each do |entertainment_application| %>
      <%= cl_image_tag entertainment_application.user.photos.first.key, height: 300, width: 300, crop: :fill, class: 'user-image'%>
    <% end %>

    <% if @artist_number.present? %>
      <% @artist_number.times do %>
        <%= image_tag "profile-base.png", alt: "profile par défaut", class: 'user-image' %>
      <% end %>
    <% end %>
  </div>

</div>