config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  get 'notification', to: 'pages#notification', as: 'notification'
  resources :entertainments, only: [ :index, :show ] do
    collection do
      get :map
    end
    resources :entertainment_applications, only: [ :new, :create ] do
      collection { get :confirmation }
    end
  end
  resources :entertainment_applications, only: [:destroy] do
    member {
      patch :accept
      patch :refused
      patch :first_accept
    }

  end
  resources :events, only: [ :new, :create, :show ]

  resource :dashboard, only: [ :show ]

  resources :chats, only: [ :index, :show ] do
    resources :messages, only: [ :create ]
  end

  resource :epk, except: [:destroy, :create, :new]

  resources :availabilities, except: [:index, :show, :destroy]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @user = current_user
    authorize @user
    @applications = current_user.entertainment_applications
    @entertainments = current_user.entertainments.where(entertainment_applications: { status: ["Accepté", "Validé"] })
  end
end

app/views/dashboards/_application_card.html.erb
 <li class="splide__slide"  >
  <div class="applications-list">
    <%= link_to entertainment_path(application.entertainment), class: "application-card" do %>
      <div class="application-card-image">
        <% if application.entertainment.event.photo.attached? %>
          <%= cl_image_tag(application.entertainment.event.photo.key, alt: "Image de l'événement", class: "application-card-img") %>
        <% else %>
          <%= image_tag "default_event.jpg", alt: "Image par défaut", class: "application-card-img" %>
        <% end %>

        <div class="status"><p class=<%= status_class %>><%= application.status %></p></div>

      </div>
      <div class="application-card-content">
        <h3 class="application-card-title"><%= application.entertainment.event.name %></h3>
        <p class="application-card-description"><%= application.entertainment.event.description %></p>
      </div>
    <% end %>
  </div>
</li>

app/views/dashboards/_event_card.html.erb
 <li class="splide__slide">
  <div class="applications-list">
    <%# <%= link_to entertainment_path(application.entertainment), class: "application-card" do %>
      <div class="application-card-image">
        <% if event.photo.attached? %>
          <%= cl_image_tag(event.photo.key, alt: "Image de l'événement", class: "application-card-img") %>
        <% else %>
          <%= image_tag "default_event.jpg", alt: "Image par défaut", class: "application-card-img" %>
        <% end %>

        <%# <div class="status"><p class=<%= status_class %>
        <%# ><%= application.status</p></div> %>

      </div>
      <div class="application-card-content">
        <h3 class="application-card-title"><%= event.name %></h3>
        <p class="application-card-description"><%= event.description %></p>
      </div>
  </div>
</li>

app/views/dashboards/show.html.erb
<% if @user.role == "artiste"%>
  <%= month_calendar(attribute: :starts_at, events: @entertainments) do |date, entertainments|%>
    <% if entertainments.any? %>
      <%= link_to entertainment_path(entertainments.first), class: "calendar-accepted" do %>
        <%= date.day %>
      <% end %>
    <% else %>
      <%= date.day %>
    <% end %>
  <% end %>
<% else %>
  <%= cl_image_tag @user.photos.first.key, alt: @user.last_name, class: "event-image"%>
<% end %>
<div class="container-dashboard">

  <div class="artist-profile">
    <div class="artist-profile-photo-group">
        <%= cl_image_tag @user.photos.first.key, alt: @user.artist_name, class: "artist-profile-photo rounded-circle" %>
    </div>

    <h1 class="artist-profile-name"><%= @user.artist_name %></h1>
    <p class="artist-profile-bio"><%= @user.bio %></p>
  </div>

    <%# <h2>Mes propositions en attente</h2> %>

    <%# <h2>Mes candidatures en accepté</h2> %>

    <h2>Mes événements à venir</h2>

    <section class="splide" data-controller="carousel" aria-label="Splide Basic HTML Example">
      <div class="splide__track">
        <ul class="splide__list">
          <% if @user.role == "artiste" %>
            <% @applications.where(status: "Accepté").each do |application| %>
            <%= render "application_card", application: application, status_class: "application-card-status-accepted" %>
            <% end %>
            <% @applications.where(status: "Validé").each do |application| %>
            <%= render "application_card", application: application, status_class: "application-card-status-validate" %>
            <% end %>
          <% else %>
            <% @user.events.each do |event| %>
              <%= render "event_card", event: event %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </section>

    <% if @applications.where(status: "Proposé").empty? %>
      <h2 class= "d-none">Proposition en attente de ma confirmation</h2>
    <% else %>
      <h2>Proposition en attente de ma confirmation</h2>

      <section class="splide" data-controller="carousel" aria-label="Splide Basic HTML Example">
        <div class="splide__track">
          <ul class="splide__list">
            <% @applications.where(status: "Proposé").each do |application| %>
            <%= render "application_card", application: application, status_class: "application-card-status-proposed" %>
            <% end %>
          </ul>
        </div>
      </section>
    <% end %>
    <%# <h2>Mes proposition validé</h2>

    <section class="splide" data-controller="carousel" aria-label="Splide Basic HTML Example">
      <div class="splide__track">
        <ul class="splide__list">
          <% @applications.where(status: "Validé").each do |application| %>
          <%# <%= render "application_card", application: application, status_class: "application-card-status-validate" %>
          <%# <% end %>
        <%# </ul>
      </div>
    </section>  %>

    <% if @applications.where(status: "En cours").empty? %>
      <h2 class="d-none">Mes candidatures en attente</h2>
      <p class="text-center">Candidate aux événements directement depuis la home page</p>
    <% else %>
      <h2>Mes candidatures en attente</h2>

      <section class="splide" data-controller="carousel" aria-label="Splide Basic HTML Example">
        <div class="splide__track">
          <ul class="splide__list">
            <% @applications.where(status: "En cours").each do |application| %>
            <%= render "application_card", application: application, status_class: "application-card-status-pending" %>
            <% end %>
          </ul>
        </div>
      </section>
    <% end %>





    <h2 id="epk-title">Mon EPK</h2>
    <%# <div class= "d-flex justify-content-center align-items-center"> %>
    <div class="flex-space-around-simple">
      <button class= "btn-white-dashboard">
        <%= link_to edit_epk_path do %>
          Modifier
        <% end %>
      </button>
      <button class= "btn-white-dashboard">
        <%= link_to epk_path do %>
          Visualiser
        <% end %>
      </button>
    </div>

    <div class= "d-flex justify-content-center align-items-center">
      <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "top-right-btn" %>
    </div>
</div>